### ISSUE TITLE
¿Se puede pasar datos desde un hijo a un padre en Reac.js?

### ISSUE THREAD

**Issue by renatojobal** [renatojobal/proyecto_thanos#16]
En el código se necesita pasar información desde un componente hijo hacia uno padre.

Más específicamente el componente de `CharacterContainer` (hijo) necesita modificar el estado de `CharacterPage` (padre) para indicarle `imageURL` y `description`. Estos datos son compartidos por el `Modal` para mostrarlos.

¿Se puede hacer esto o existe una mejor forma de resolver el problema?

**Comment by mvinan** [comment]
Tienes algunas maneras de hacerlo, una es usando un store global y conjuntamente una librería como (Redux) que sirve muy bien, pero como es un proyecto pequeño puedes hacerlo con el (React.Context) puedes crear un contexto.

**Comment by mvinan** [comment]
https://es.reactjs.org/docs/context.html
